-- LiveRank Supabase setup
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  total_score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.score_logs (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.participants(id) on delete cascade,
  station_number integer not null,
  points_awarded integer not null,
  created_at timestamptz not null default now()
);

alter table public.participants enable row level security;
alter table public.score_logs enable row level security;

drop policy if exists "public can read participants" on public.participants;
create policy "public can read participants" on public.participants for select to anon, authenticated using (true);

drop policy if exists "public can read score logs" on public.score_logs;
create policy "public can read score logs" on public.score_logs for select to anon, authenticated using (true);

create or replace function public.award_points(
  p_participant_id uuid,
  p_station_number integer,
  p_points integer
)
returns public.participants
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_participant public.participants;
begin
  if p_points not in (1,2,3) then
    raise exception 'Invalid point value';
  end if;
  if p_station_number < 1 or p_station_number > 12 then
    raise exception 'Invalid station';
  end if;

  update public.participants
  set total_score = total_score + p_points
  where id = p_participant_id
  returning * into updated_participant;

  if updated_participant.id is null then
    raise exception 'Participant not found';
  end if;

  insert into public.score_logs(participant_id, station_number, points_awarded)
  values (p_participant_id, p_station_number, p_points);

  return updated_participant;
end;
$$;

grant execute on function public.award_points(uuid, integer, integer) to anon, authenticated;

-- Reset the current event while keeping the participant list.
create or replace function public.reset_event()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.score_logs;
  update public.participants set total_score = 0;
end;
$$;

grant execute on function public.reset_event() to anon, authenticated;

-- Realtime: add participants to the realtime publication only if not already present.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'participants'
  ) then
    alter publication supabase_realtime add table public.participants;
  end if;
end $$;

-- Example participants. Delete these and add your real names if desired.
insert into public.participants (name) values
  ('Participant 1'), ('Participant 2'), ('Participant 3'), ('Participant 4')
on conflict do nothing;
